#!/usr/bin/gawk -OSf
# colout '-po' '^([Zz]:)?([\\/.]*[^(]+)\(([0-9]+),?([0-9]+)\):( note)?( warning ?\w*)?( error ?\w*)?' 'n' 'b' 'y' 'y' 'c' 'y,o' 'r,o'

# created dim. nov. 17 20:46:03 2024

BEGIN {
esc_reset = "\033[0m"
colors0[0] = ";0"
colors0[1] = ";34"
colors0[2] = ";33"
colors0[3] = ";33"
colors0[4] = ";36"
colors0[5] = ";33;1"
colors0[6] = ";31;1"
nb_colors0 = 7
}

{
s = ""
if (match($0, /^([Zz]:)?([\\\/.]*[^(]+)\(([0-9]+),?([0-9]+)\):( note)?( warning ?\w*)?( error ?\w*)?/, a)) {
	n = length(a) / 3
	if (n == 1) {
		i = 0
		ic = 0
		s = s substr($0, 0, RSTART - 1) "\033[" colors0[ic % nb_colors0] "m" a[i] esc_reset
	} else {
		p = 1
		for (i = 1; i < n; ++i) {
			start = a[i, "start"]
			if (start == null) {
				++n
				continue
			}
			ic = i - 1
			s = s substr($0, p, start - p) "\033[" colors0[ic % nb_colors0] "m" a[i] esc_reset
			p = start + a[i, "length"]
		}
		s = s substr($0, p, RSTART + RLENGTH - p)
	}
	$0 = substr($0, RLENGTH + RSTART)
}
print s $0
}

